_target_: pytorch_lightning.Trainer

# default values for all trainer parameters
checkpoint_callback: True
default_root_dir: null
gradient_clip_val: 0
process_position: 0
num_nodes: 1
num_processes: 1

gpus: -1
auto_select_gpus: True
tpu_cores: null
log_gpu_memory: null
progress_bar_refresh_rate: 1
overfit_batches: 0.0
track_grad_norm: -1
check_val_every_n_epoch: 1
fast_dev_run: False
accumulate_grad_batches: ${setup.accumulate_grad_batches}

max_epochs: 10
min_epochs: 1
max_steps: null
min_steps: null
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
val_check_interval: 1.0
flush_logs_every_n_steps: 1000
log_every_n_steps: 1000
accelerator: null
sync_batchnorm: False
precision: ${setup.precision}
weights_summary: "top"
weights_save_path: null

num_sanity_val_steps: 0
truncated_bptt_steps: null
resume_from_checkpoint: null
profiler: null
benchmark: True
deterministic: True
reload_dataloaders_every_epoch: False
auto_lr_find: False
replace_sampler_ddp: True
terminate_on_nan: False
auto_scale_batch_size: False
prepare_data_per_node: True
plugins: null
amp_backend: "native"
amp_level: "O2"
move_metrics_to_cpu: False
