_target_: src.model.lm.LanguageModel

defaults:
  - optimizer: hf_adamw
  - scheduler: linear_with_warmup

model: lm
arch: google/bigbird-roberta-base
dataset: ${data.dataset}

num_freeze_layers: 0
freeze_epochs: -1

expl_reg: True
train_topk: [1, 5, 10, 20, 50]
eval_topk: [1, 5, 10, 20, 50]
expl_reg_freq: 1
task_wt: 1.0

comp_criterion: null
comp_margin: null
comp_target: False
comp_wt: 0.0

suff_criterion: null
suff_margin: null
suff_target: False
suff_wt: 0.0

log_odds: False
log_odds_target: False

plaus_criterion: bce
plaus_margin: 0.1
plaus_wt: 0.0

explainer_type: lm
expl_head_type: linear
expl_head_mlp_hidden_dim: null
expl_head_mlp_hidden_layers: null
expl_head_mlp_dropout: 0.0
expl_head_mlp_layernorm: False
attr_algo: null
attr_pooling: null
attr_mlp_hidden_dim: null
attr_mlp_hidden_layers: null
attr_mlp_dropout: null
attr_mlp_layernorm: null
ig_steps: null
internal_batch_size: null
return_convergence_delta: False
gradshap_n_samples: null
gradshap_stdevs: null

fresh: False
fresh_extractor: null

l2e: False
l2e_wt: 0.0
l2e_criterion: null
l2e_classes: null

a2r: True
a2r_wt: 0.0
a2r_criterion: jsd
a2r_task_out: sum

save_outputs: False
exp_id: null

measure_attrs_runtime: False